Fix memory leaks
PenteractStudios/Tesseract pull request #169
Opened 2021-05-03 21:24 UTC by JaimeBea

2021-05-03 22:52 UTC, FrancPS requested changes
Genious.
I've found yet 2 more leaks, if I load level1.scene, and then close the engine

2021-05-04 08:49 UTC, lowysole approved these changes

2021-05-04 08:57 UTC, Jordi-Gil approved these changes

2021-05-04 20:53 UTC, FrancPS approved these changes

2021-05-04 21:49 UTC, merged