Established Script Teleporter.h
PenteractStudios/Tesseract pull request #177
Opened 2021-05-04 19:26 UTC by devildrake

Established Float3 exception for Member exposing on editor inspector

Created Teleporter.h, which allows a referenced gameobject to be teleported from its transform.position to the established one (reference and Vector3 exposed on Editor). This is actioned pressing T key.

2021-05-04 21:14 UTC, JaimeBea approved these changes

2021-05-04 21:22 UTC, Jordi-Gil requested changes
If I expose a float3 is loaded correctly.
![image](https://user-images.githubusercontent.com/24542154/117071147-f7a7c400-ad2e-11eb-952f-20d582ae8102.png)

If I click on Play, the float3 is updated correctly. 

https://user-images.githubusercontent.com/24542154/117071544-8a486300-ad2f-11eb-90a9-e58074d288fa.mp4


But when I click stop, the ImGui shows me (0,0,0)

![image](https://user-images.githubusercontent.com/24542154/117071332-45243100-ad2f-11eb-8413-9c694894c8dc.png)

2021-05-05 08:11 UTC, devildrake commented
> If I expose a float3 is loaded correctly.
> ![image](https://user-images.githubusercontent.com/24542154/117071147-f7a7c400-ad2e-11eb-952f-20d582ae8102.png)
> 
> If I click on Play, the float3 is updated correctly.
> 
>  error.mp4 
> But when I click stop, the ImGui shows me (0,0,0)
> 
> ![image](https://user-images.githubusercontent.com/24542154/117071332-45243100-ad2f-11eb-8413-9c694894c8dc.png)

Fixed it but declaring local variables inside a switch seems a little anti aesthetic, any suggestions are welcome
![Suggestions](https://user-images.githubusercontent.com/23354524/117113029-374fc980-ad8a-11eb-80e0-59c08c5da29a.png)

2021-05-05 09:14 UTC, Jordi-Gil approved these changes
Works!

2021-05-05 09:37 UTC, merged