Feature/cu-hn6q3b create clip editor UI
PenteractStudios/Tesseract pull request #264
Opened 2021-05-15 18:24 UTC by JoanMarcBardes

2021-05-15 19:32 UTC, Jordi-Gil commented
Stop! Merge into develop not Master @JoanMarcBardes

2021-05-16 21:03 UTC, FrancPS requested changes
As Jordi says

2021-05-18 12:53 UTC, JaimeBea approved these changes

2021-05-18 12:53 UTC, JaimeBea commented on Project/Source/Resources/ResourceClip.cpp
> +	SetBeginIndex(beginIndex);
There is no need to change 'beginIndex' and 'endIndex' into signed integers. You can use ImGui::InputScalar for unsigned integers.

2021-05-19 19:51 UTC, FrancPS approved these changes

2021-05-21 16:51 UTC, JoanMarcBardes commented
@JaimeBea 
I tested this branch with feature/CU-jd4mpr-implement-resource-meta-files and works fine when saving the resource, so every thing is right.

2021-05-21 16:53 UTC, merged