Bugfix: UI Pivot behaviour with new canvas refactor
PenteractStudios/Tesseract pull request #269
Opened 2021-05-17 19:32 UTC by AHinojal

We have fixed the pivot! We can rotate a 2D object around a pivot despite the current position, scale, size and anchors ;)

I deleted the option in the editor panel to put pivot mode or center mode and if you want the center, you have to put (0.5,0.5) in the pivot (its by default in that position)
When scale and change the pivot, recompute the position to put the object in the center...because if you scale an object after changed the pivot, the object will have a little offset.
Also, you can't rotate, change the pivot and rotate again like in Unity...maybe we can put this option in the future if we have plenty of time, because honestly, I don't think we will use so much the pivot configuration.

If I see any bugs or something like that, put it Clickup like a hotfix! ;)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/25251729/118544004-51f44c00-b755-11eb-8e22-a7e1732b67e3.gif)

2021-05-18 12:50 UTC, JaimeBea approved these changes

2021-05-18 12:50 UTC, JaimeBea commented on Game/Assets/Shaders/uiShader.glsl
> +#endif
The .glsl shaders that are being added in this PR should be removed. They are deprecated.

2021-05-18 12:51 UTC, JaimeBea commented
Make sure to merge develop into the branch first.

2021-05-18 17:43 UTC, JaimeBea reviewed
You removed some shaders you didn't have to remove. Be careful.

2021-05-18 18:03 UTC, AHinojal commented
Fix all problems with the shaders folder and glsl files in the last commit with the files that we have in the Shaders folder in the develop branch right now. ;)

2021-05-19 13:04 UTC, FrancPS approved these changes
Works as intended and no compilation warnings, good job.

As always, test a scene in GAME if you haven't.

I'll include the missing functionality in QA list.

2021-05-19 14:22 UTC, AHinojal commented
> Works as intended and no compilation warnings, good job.
> 
> As always, test a scene in GAME if you haven't.
> 
> I'll include the missing functionality in QA list.

Luckily you have say that I should take a look testing in GAME and 2D option, because the fucking Bounding Box was wrong when rotate with a pivot different than (0.5,0.5) 😓🤦‍♂️ My fault!

When I fix this problem, I will request the review and put a comment with a proof

2021-05-20 13:26 UTC, devildrake approved these changes

2021-05-26 14:06 UTC, FrancPS requested changes
Fix errors appearing in GAME

2021-05-27 15:06 UTC, JaimeBea approved these changes

2021-05-27 15:06 UTC, JaimeBea commented on Project/Source/Components/ComponentBoundingBox2D.cpp
> +		//worldAABB.maxPoint += windowPos;
If this is not necessary anymore it could be removed. Check if it works in Game.

2021-05-29 09:03 UTC, devildrake requested changes
There appears to be something wrong with the scaling when the pivot X is not 0.5, from gameplay it appears we only need the pivot to work properly on Y axis, which it does, but this is still a problem

https://user-images.githubusercontent.com/23354524/120064624-79101f00-c06d-11eb-9709-bcb4e64e0cb8.mp4

2021-06-02 10:27 UTC, AHinojal commented
Well, I reopen the PR fixing the pivot for this last sprint! I tested in Debug, Release and Game the scene that I put here in this message.
You can scale the object from a pivot and the bounding box works correctly (to @devildrake)
Also I put an checkbox in the inspector in Canvas & BoundingBox2D components to draw the object's gizmo in 3D.

Bud luck for us, fix the bounding box (rotate behaviour specially) its more difficult that I thought...We will have to transform the boundingbox from AABB2D to a OBB (OBB2D's implemetation is empty xD) and like its not our priority and right now this feature we dont need it, we can try to fix it later.

Download TestScene: 
[TEST_PivotingScene.zip](https://github.com/PenteractStudios/Tesseract/files/6583697/TEST_PivotingScene.zip)

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/25251729/120464823-a32f4d00-c39d-11eb-89fb-f8c66ffa2185.gif)
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/25251729/120464696-81ce6100-c39d-11eb-9010-e42cae6718aa.gif)

2021-06-02 13:27 UTC, JaimeBea submitted a review, later dismissed

2021-06-02 13:27 UTC, JaimeBea commented on Project/Source/Components/UI/ComponentTransform2D.cpp
> +#include <Utils/Logging.h>
Leaks should be the last include

2021-06-02 14:25 UTC, AHinojal commented on Project/Source/Components/UI/ComponentTransform2D.cpp
> +#include <Utils/Logging.h>
Perfect! Fix it in the last commit ;)

2021-06-02 14:26 UTC, JaimeBea approved these changes

2021-06-03 13:57 UTC, devildrake approved these changes
Wonderful! Good job guys!

2021-06-03 21:02 UTC, FrancPS approved these changes
There is a minor issue about scaling UI elements and translating the scale to its children BB.

Added as another task is clickup since its a minor issue, and a feature that will probably not be used.

2021-06-03 21:04 UTC, merged