Remove need for Assets folder in Game configuration
PenteractStudios/Tesseract pull request #310
Opened 2021-05-30 18:16 UTC by JaimeBea

With this PR we will no longer need the Assets folder when releasing the game. A few things were changed:
- Scenes are now loaded by UID from scripts (this will require a change to the scripts and scenes)
- Shaders bin file is no longer created in the Game configuration (this was a bug)
- Resource meta files now contain the type of resource. (The Library folder needs to be deleted)

2021-05-31 14:51 UTC, Jordi-Gil approved these changes
Approved without testing.

2021-06-01 08:27 UTC, lowysole approved these changes
Shader part checked

2021-06-01 14:32 UTC, jcarlos0305 submitted a review, later dismissed

2021-06-03 22:56 UTC, Jordi-Gil requested changes
I have not been able to get it to work in "Game". In engine, the change to expose scene UID works perfectly.

2021-06-04 21:00 UTC, Jordi-Gil approved these changes

2021-06-04 21:02 UTC, jcarlos0305 approved these changes

2021-06-04 21:29 UTC, lowysole approved these changes

2021-06-04 21:31 UTC, merged