HotfixSphere
PenteractStudios/Tesseract pull request #322
Opened 2021-06-03 17:33 UTC by telmiuse

2021-06-03 19:20 UTC, telmiuse commented
![Gw9Wz2sMgm](https://user-images.githubusercontent.com/61976005/120700093-83894900-c4b1-11eb-974f-389627b32f0d.gif)

2021-06-03 20:14 UTC, JaimeBea approved these changes

2021-06-04 09:52 UTC, FrancPS approved these changes

2021-06-04 14:36 UTC, telmiuse commented
The delay time in Loop Just work in the first time, once stard does not affect it .

2021-06-04 21:40 UTC, JaimeBea approved these changes

2021-06-04 21:50 UTC, Jordi-Gil requested changes

2021-06-04 21:50 UTC, Jordi-Gil commented on Project/Source/Components/ComponentParticleSystem.cpp
> +#define JSON_TAG_TEXTURE_REVERSEEFFECT "reverseEffect"
Tag in lowcase

2021-06-04 21:50 UTC, Jordi-Gil commented on Project/Source/Components/ComponentParticleSystem.cpp
> +	distanceReverse = jComponent[JSON_TAG_TEXTURE_REVERSEEFFECT];
reverseEffect and distanceReverse swap

2021-06-04 21:50 UTC, Jordi-Gil commented on Project/Source/Components/ComponentParticleSystem.cpp
> +	jComponent[JSON_TAG_TEXTURE_REVERSEEFFECT] = distanceReverse;
reverseEffect and distanceReverse swap

2021-06-04 21:50 UTC, Jordi-Gil commented on Project/Source/Components/ComponentParticleSystem.h
> +	float coneRadiusUp = 1;
float initialize as an integer. Set 1.0f preferred

2021-06-04 21:50 UTC, JaimeBea approved these changes

2021-06-04 23:01 UTC, Jordi-Gil approved these changes

2021-06-04 23:02 UTC, lowysole submitted a review, later dismissed

2021-06-04 23:13 UTC, merged