Bugfix/cu kxdjfv fix two state machine
PenteractStudios/Tesseract pull request #323
Opened 2021-06-03 20:01 UTC by JoanMarcBardes

2021-06-03 20:17 UTC, JaimeBea submitted a review, later dismissed

2021-06-03 21:27 UTC, Jordi-Gil requested changes
The engine crashes when a game object that have a ComponentAnimation with an StateMachine resource attached

2021-06-04 19:58 UTC, JaimeBea approved these changes

2021-06-04 21:27 UTC, Jordi-Gil approved these changes
Tested! 😄

2021-06-04 21:34 UTC, lowysole approved these changes

2021-06-04 21:34 UTC, merged