Trail orientatio fix
PenteractStudios/Tesseract pull request #419
Opened 2021-09-02 09:13 UTC by telmiuse

2021-09-02 13:14 UTC, JaimeBea submitted a review, later dismissed

2021-09-02 13:14 UTC, JaimeBea commented on Project/Source/Utils/Trail.h
> +	Quat mainRotation;
The quaternions should be initialized to avoid garbage values.

2021-09-03 12:27 UTC, FrancPS submitted a review, later dismissed

2021-09-04 11:36 UTC, lowysole requested changes

2021-09-04 11:36 UTC, lowysole commented on Project/Source/Utils/Trail.cpp
> +	float3 currentDirection = (previousPosition - currentPosition).Normalized();
direction is  (currentPosition -previousPosition). Care then with the Perpendicular() result

2021-09-04 11:36 UTC, lowysole commented on Project/Source/Utils/Trail.cpp
> +}
I checked it again and it's incorrect. The formula for 3º dimension distance is using square roots:

`if (B.Distance(A) > vertexDistance) return true;  // (B-A -> current - previous)`

or an optimal way:

`if (B.DistanceSq(A) > vertexDistance * vertexDistance) return true;`

2021-09-06 14:19 UTC, JaimeBea approved these changes

2021-09-07 08:39 UTC, FrancPS submitted a review, later dismissed

2021-09-08 09:15 UTC, lowysole commented
Not Compiling.

2021-09-08 09:18 UTC, lowysole approved these changes

2021-09-08 09:20 UTC, JaimeBea approved these changes

2021-09-08 12:41 UTC, FrancPS approved these changes

2021-09-09 11:36 UTC, merged