Particle System improvements v5
PenteractStudios/Tesseract pull request #464
Opened 2021-10-04 08:40 UTC by lowysole

- [fix] Refractor of rotations
- [fix] Box emitter now working
- [feature] Velocity over lifetimne
- [feature] New gravity model

2021-10-04 09:55 UTC, JaimeBea approved these changes
Everything works perfectly. One possible improvement:

Using curves with velocity over lifetime only allows positive numbers. Maybe we should allow to edit the min value too?

2021-10-04 10:02 UTC, JaimeBea requested changes

2021-10-04 10:02 UTC, JaimeBea commented on Project/Source/Components/ComponentParticleSystem.cpp
> +#define JSON_TAG_VELOCITY_SPEED_MODIFIER_CURVE "VelocitySpeedModifierCurve"
These tags aren't being saved nor loaded

2021-10-04 11:15 UTC, lowysole commented
> Everything works perfectly. One possible improvement:
> 
> Using curves with velocity over lifetime only allows positive numbers. Maybe we should allow to edit the min value too?

You can have negative values but in the curve, you will always have a range from [-, 0] or [0, +], not both together. I have the improvement, but the problem is that it will affect all the effects that are in the scene. I have the same problem with an improvement of the scale. So sadly, I think we will have to keep it this way

2021-10-04 13:21 UTC, FrancPS submitted a review, later dismissed

2021-10-05 08:37 UTC, JaimeBea submitted a review, later dismissed

2021-10-05 16:41 UTC, telmiuse approved these changes

2021-10-05 16:48 UTC, JaimeBea approved these changes

2021-10-05 19:40 UTC, FrancPS approved these changes

2021-10-06 09:17 UTC, merged